---
title: "My websites designing experience"
description: |
  Over the years, I have designed a couple of professional websites using HTML & CSS and R packages. Here, I share a bit about my experiences using the different platforms.
author:
  - name: Stephen Balogun
    url: https://taiye.netlify.app
date: 2020-02-29
lastMod: 2022-01-11
image:
  caption: 'Image credit: [**Cymax Media**](https://www.cymaxmedia.com/web-development-vs-web-design/)'
  focal_point: ""
  placement: 2
  preview_only: false
output:
  distill::distill_article:
    self_contained: false
categories:
  - learning journey
---


## Introduction

I started my data science learning in the year 2016. Initially, I came into contact with Epi-Info through a senior colleague. Along the line, I stumbled on the [Data Science Specialization course on Coursera offered by the John Hopkins Bloomberg School of Public Health](https://www.coursera.org/specializations/jhu-data-science). Boom!! I fell in love completely. Coming from someone without prior computer programming or website designing experience (I came from practically zero), and a practicing medical professional, I had initial turbulence. But my perseverance got the better of me.

My initial interest was in the computing power of R, but I steadily became interested in other aspects including using [R for slides presentation](https://rmarkdown.rstudio.com/lesson-11.html), interactive charts, etc. The desire to customize the appearances steadily led me into learning about CSS and HTML. That was the beginning of my website design journey.  

So far, I have built several sites, all consisting of static web pages. I had a break from data science for close to two years to develop other skills. I came back to R earlier this year and I have been trying to catch-up with the rapidly developing and ever increasing knowledge of R which I usually find overwhelming and intriguing at the same time. Here I share my experience building the three sites, one from the scratch (HTML and CSS) while others have been from the RStudio environment using {rmarkdown} {blogdown} and {distill}.  

## First Website - [RHDS](https://r4hds.github.io/)

Built in May 2017 with R using the [Rmarkdown](https://rmarkdown.rstudio.com/) package. Thanks to the detailed [documentations](https://rmarkdown.rstudio.com/articles.html), I was able to build the site in a short time. I had to learn a little of HTML and CSS thanks to [w3schools](https://www.w3schools.com/) tutorials. [Github](https://github.com/) provided the hosting platform and a repository for my files. Though it has not been maintained in a while (I intend to periodically update it from this year), I use the site to share my analysis of healthcare data of open source data repositories of WHO and other United Nation agencies.  


## Second Website - [Teehwy's world](http://balogunst.byethost32.com/index.html#)  

Following the success of my first website, and my initial knowledge of CSS and HTML, I became more curious about learning HTML and CSS. Thanks to the Coursera course offered by the [University of Michigan](https://www.coursera.org/specializations/web-design). I began building my second website from the scratch writing the HTML and CSS codes myself using both [Visual Studio 2017](https://visualstudio.microsoft.com/) and [Visual Studio Code](https://code.visualstudio.com/). Even though the site has only few web pages, I thoroughly enjoyed the experience of building a site from the scratch, and ensuring compliance with [validatorW3](https://validator.w3.org/). While [Github](https://github.com) provides the repository, the site is currently hosted on [byethost](). I will be moving it away from Byethost to either [Netlify](https://netlify.com) or [Github](https://github.com) in the next couple of months and will update this page accordingly.


## Third Website - [Balogun Stephen Taiye](https://taiye.rbind.io/)  


Built in February 2020 using the R package [blogdown](https://bookdown.org/yihui/blogdown) and Hugo.  There are pre-designed powerful themes that provide options from simple to complex that makes the experience a whole lost faster and easier. I am currently using the [Academic theme](https://sourcethemes.com/academic), and I am literarily swept off my feet. The site is hosted on [netlify](https://netlify.com) with github providing the [repository](https://github.com/stbalo2002/website2) If you are ever interested in building a website using [blogdown](https://bookdown.org/yihui/blogdown) and [Hugo](https://gohugo.io/), I think you will also find the links below very useful:  

- [Up & Running with blogdown](https://alison.rbind.io/post/2017-06-12-up-and-running-with-blogdown/) by Alison Hill  

- [https://amber.rbind.io/2016/12/19/website/](https://amber.rbind.io) by Amber Thomas  


## Conclusion

I think it is a good idea for every person interested in building websites to have a basic idea of how to build a site from the scratch. But for persons who are also interested in data science, the data science software can also be leveraged upon to develop powerful static websites that can be further customized for personal touch and appearance.  

While I am not sure if I will venture into dynamic websites in the near future, I am definitely in love with the [blogdown](https://bookdown.org/yihui/blogdown/) package for website building and I intend to continue to use it in the main time.
